function [H,Hso,dH,d2H,out] = DB_PA_Hamiltonian(r,phi,th,pr,pphi,pth,a)
	% Basically Kerr Hamiltonian in BL coordinates
	% might turn out useful

    %[r,phi,th,pr,pphi,pth] = DB_coords_cart2spherical(X(1),X(2),X(3),P(1),P(2),P(3));
    [A,dA,Gs,dGs,R,dRf,Df,dD] = metric_coeff(r,phi,th,pr,pphi,pth,a);
    out.A = A;
    out.D = Df;
    out.S = r.^2+a.^2.*cos(th).^2;

    dAdr = dA.dr;
    dAdth = dA.dth;
    d2Adrdth = dA.drdth;
    d2Ad2r = dA.d2r;
    dGsdr = dGs.dr;
    dGsdth = dGs.dth;
    d2Gsdrdth = dGs.drdth;
    d2Gsd2r = dGs.d2r;

    dDf = dD.dr;
    d2Df = dD.d2r;
    dR = dRf.dr;
    d2R = dRf.d2r;

    Horb = (A.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+pphi.^2.*(r.^2+a.^2.*cos(th).^2).*(R+ ...
        a.^2.*Df.*cos(th).^2).^(-1).*csc(th).^2)).^(1/2);
    %Hso = a.*Gs.*sin(th).*(pth.^2+pphi.^2.*csc(th).^2).^(1/2);
    Hso = a.*Gs.*pphi;

    H = Horb + Hso;

    dHorbdr = (1/2).*(A.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))).^(-1/2).*(A.*((-2).*Df.* ...
        pr.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+(-2).*pth.^2.*r.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-2)+dDf.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+ ...
        (-1).*(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(dR+a.^2.*cos(th).^2.*sin( ...
        th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-2)+2.*r.*(R+a.^2.* ...
        r.*cos(th).^2.*sin(th).^2).^(-1))+dAdr.*(1+Df.*pr.^2.*(r.^2+a.^2.* ...
        cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+ ...
        a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^( ...
        -1)));

    dHorbdth = (1/2).*(A.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))).^(-1/2).*(dAdth.*(1+Df.* ...
        pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th) ...
        .^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th) ...
        .^2.*sin(th).^2).^(-1))+(1/4).*a.^2.*A.*((-8).*pphi.^2.*cos(th).* ...
        sin(th).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1)+4.*Df.*pr.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-2).*sin(2.*th)+4.*pth.^2.*(r.^2+a.^2.* ...
        cos(th).^2).^(-2).*sin(2.*th)+(-1).*r.*(a.^2.*pphi.^2+2.*r.^2+ ...
        a.^2.*pphi.^2.*cos(2.*th)).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^( ...
        -2).*sin(4.*th)));

    dHorbdpth = A.*pth.*(r.^2+a.^2.*cos(th).^2).^(-1).*(A.*(1+Df.*pr.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+( ...
        r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-1))).^(-1/2);

    dHorbdpphi = a.^2.*A.*pphi.*cos(th).^2.*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^( ...
        -1).*(A.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))).^(-1/2);

    dHsodr = a.*dGsdr.*cos(th).*(pth.^2+pphi.^2.*csc(th).^2).^(1/2);

    dHsodth = a.*(pth.^2+pphi.^2.*csc(th).^2).^(-1/2).*(dGsdth.*cot(th).*( ...
        pth.^2+pphi.^2.*csc(th).^2)+(-1).*Gs.*(pth.^2+pphi.^2.*csc(th).^4) ...
        ).*sin(th);

    dHsodpth = a.*Gs.*pth.*cos(th).*(pth.^2+pphi.^2.*csc(th).^2).^(-1/2);

    dHsodpphi = a.*Gs.*pphi.*cot(th).*csc(th).*(pth.^2+pphi.^2.*csc(th).^2).^( ...
        -1/2);

    d2Horbd2r = (1/4).*(A.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))).^(-3/2).*(2.*A.*(1+Df.* ...
        pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th) ...
        .^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th) ...
        .^2.*sin(th).^2).^(-1)).*(A.*(8.*Df.*pr.^2.*r.^2.*(r.^2+a.^2.*cos( ...
        th).^2).^(-3)+8.*pth.^2.*r.^2.*(r.^2+a.^2.*cos(th).^2).^(-3)+(-2) ...
        .*Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-2)+(-2).*pth.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-2)+(-4).*dDf.*pr.^2.*r.*(r.^2+a.^2.*cos(th) ...
        .^2).^(-2)+d2Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+2.*(r.^2+ ...
        a.^2.*pphi.^2.*cos(th).^2).*(dR+a.^2.*cos(th).^2.*sin(th).^2).^2.* ...
        (R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-3)+(-1).*d2R.*(r.^2+a.^2.* ...
        pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-2)+( ...
        -4).*r.*(dR+a.^2.*cos(th).^2.*sin(th).^2).*(R+a.^2.*r.*cos(th) ...
        .^2.*sin(th).^2).^(-2)+2.*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^( ...
        -1))+2.*dAdr.*((-2).*Df.*pr.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+( ...
        -2).*pth.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+dDf.*pr.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+(-1).*(r.^2+a.^2.*pphi.^2.*cos(th).^2).*( ...
        dR+a.^2.*cos(th).^2.*sin(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-2)+2.*r.*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))+ ...
        d2Ad2r.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1)))+(-1).*(A.*((-2).*Df.* ...
        pr.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+(-2).*pth.^2.*r.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-2)+dDf.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+ ...
        (-1).*(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(dR+a.^2.*cos(th).^2.*sin( ...
        th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-2)+2.*r.*(R+a.^2.* ...
        r.*cos(th).^2.*sin(th).^2).^(-1))+dAdr.*(1+Df.*pr.^2.*(r.^2+a.^2.* ...
        cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+ ...
        a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^( ...
        -1))).^2);

    d2Horbdrdpphi = (1/2).*a.^2.*A.*pphi.*cos(th).^2.*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-2).*(A.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+ ...
        pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th) ...
        .^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))).^(-3/2).*(2.*(1+ ...
        Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos( ...
        th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos( ...
        th).^2.*sin(th).^2).^(-1)).*((-1).*A.*(dR+a.^2.*cos(th).^2.*sin( ...
        th).^2)+dAdr.*(R+a.^2.*r.*cos(th).^2.*sin(th).^2))+(-1).*(R+a.^2.* ...
        r.*cos(th).^2.*sin(th).^2).*(A.*((-2).*Df.*pr.^2.*r.*(r.^2+a.^2.* ...
        cos(th).^2).^(-2)+(-2).*pth.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+ ...
        dDf.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+(-1).*(r.^2+a.^2.* ...
        pphi.^2.*cos(th).^2).*(dR+a.^2.*cos(th).^2.*sin(th).^2).*(R+a.^2.* ...
        r.*cos(th).^2.*sin(th).^2).^(-2)+2.*r.*(R+a.^2.*r.*cos(th).^2.* ...
        sin(th).^2).^(-1))+dAdr.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^( ...
        -1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.* ...
        cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))));

    d2Horbdrdpth = (1/2).*A.*pth.*(r.^2+a.^2.*cos(th).^2).^(-2).*(A.*(1+Df.*pr.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1) ...
        +(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-1))).^(-3/2).*(2.*((-2).*A.*r+dAdr.*(r.^2+a.^2.*cos(th) ...
        .^2)).*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))+(-1).*(r.^2+a.^2.*cos(th) ...
        .^2).*(A.*((-2).*Df.*pr.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+(-2) ...
        .*pth.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+dDf.*pr.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+(-1).*(r.^2+a.^2.*pphi.^2.*cos(th).^2).*( ...
        dR+a.^2.*cos(th).^2.*sin(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-2)+2.*r.*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))+dAdr.* ...
        (1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.* ...
        cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.* ...
        cos(th).^2.*sin(th).^2).^(-1))));
        
    d2Horbdrdth = (1/4).*(A.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))).^(-3/2).*((-1).*(A.*((-2) ...
        .*Df.*pr.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+(-2).*pth.^2.*r.*( ...
        r.^2+a.^2.*cos(th).^2).^(-2)+dDf.*pr.^2.*(r.^2+a.^2.*cos(th).^2) ...
        .^(-1)+(-1).*(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(dR+a.^2.*cos(th) ...
        .^2.*sin(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-2)+2.*r.* ...
        (R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))+dAdr.*(1+Df.*pr.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1) ...
        +(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-1))).*(dAdth.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+ ...
        pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th) ...
        .^2).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))+(1/4).*a.^2.*A.*( ...
        (-8).*pphi.^2.*cos(th).*sin(th).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-1)+4.*Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-2).*sin(2.*th) ...
        +4.*pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-2).*sin(2.*th)+(-1).*r.*( ...
        a.^2.*pphi.^2+2.*r.^2+a.^2.*pphi.^2.*cos(2.*th)).*(R+a.^2.*r.*cos( ...
        th).^2.*sin(th).^2).^(-2).*sin(4.*th)))+2.*A.*(1+Df.*pr.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+( ...
        r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-1)).*(dAdth.*((-2).*Df.*pr.^2.*r.*(r.^2+a.^2.*cos(th).^2) ...
        .^(-2)+(-2).*pth.^2.*r.*(r.^2+a.^2.*cos(th).^2).^(-2)+dDf.*pr.^2.* ...
        (r.^2+a.^2.*cos(th).^2).^(-1)+(-1).*(r.^2+a.^2.*pphi.^2.*cos(th) ...
        .^2).*(dR+a.^2.*cos(th).^2.*sin(th).^2).*(R+a.^2.*r.*cos(th).^2.* ...
        sin(th).^2).^(-2)+2.*r.*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1)) ...
        +d2Adrdth.*(1+Df.*pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+pth.^2.*( ...
        r.^2+a.^2.*cos(th).^2).^(-1)+(r.^2+a.^2.*pphi.^2.*cos(th).^2).*(R+ ...
        a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1))+(1/4).*a.^2.*A.*((-32).* ...
        Df.*pr.^2.*r.*cos(th).*(r.^2+a.^2.*cos(th).^2).^(-3).*sin(th)+( ...
        -32).*pth.^2.*r.*cos(th).*(r.^2+a.^2.*cos(th).^2).^(-3).*sin(th)+ ...
        8.*pphi.^2.*cos(th).*sin(th).*(dR+a.^2.*cos(th).^2.*sin(th).^2).*( ...
        R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-2)+4.*dDf.*pr.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-2).*sin(2.*th)+4.*r.*(r.^2+a.^2.*pphi.^2.* ...
        cos(th).^2).*(dR+a.^2.*cos(th).^2.*sin(th).^2).*(R+a.^2.*r.*cos( ...
        th).^2.*sin(th).^2).^(-3).*sin(4.*th)+(-4).*r.^2.*(R+a.^2.*r.*cos( ...
        th).^2.*sin(th).^2).^(-2).*sin(4.*th)+(-1).*(a.^2.*pphi.^2+2.* ...
        r.^2+a.^2.*pphi.^2.*cos(2.*th)).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-2).*sin(4.*th))+(1/4).*a.^2.*dAdr.*((-8).*pphi.^2.*cos(th) ...
        .*sin(th).*(R+a.^2.*r.*cos(th).^2.*sin(th).^2).^(-1)+4.*Df.* ...
        pr.^2.*(r.^2+a.^2.*cos(th).^2).^(-2).*sin(2.*th)+4.*pth.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-2).*sin(2.*th)+(-1).*r.*(a.^2.*pphi.^2+2.* ...
        r.^2+a.^2.*pphi.^2.*cos(2.*th)).*(R+a.^2.*r.*cos(th).^2.*sin(th) ...
        .^2).^(-2).*sin(4.*th))));

    d2Hsod2r = a.*d2Gsd2r.*cos(th).*(pth.^2+pphi.^2.*csc(th).^2).^(1/2);

    d2Hsodrdpphi = a.*dGsdr.*pphi.*cot(th).*csc(th).*(pth.^2+pphi.^2.*csc(th).^2).^( ...
        -1/2);

    d2Hsodrdpth = a.*dGsdr.*pth.*cos(th).*(pth.^2+pphi.^2.*csc(th).^2).^(-1/2);

    d2Hsodrdth = a.*(pth.^2+pphi.^2.*csc(th).^2).^(-1/2).*(d2Gsdrdth.*cot(th).*( ...
        pth.^2+pphi.^2.*csc(th).^2)+(-1).*dGsdr.*(pth.^2+pphi.^2.*csc(th) ...
        .^4)).*sin(th);

    dHdpr_over_pr = A.*Df.*(r.^2+a.^2.*cos(th).^2).^(-1).*(A.*(1+Df.*pr.^2.*(r.^2+ ...
        a.^2.*cos(th).^2).^(-1)+pth.^2.*(r.^2+a.^2.*cos(th).^2).^(-1)+ ...
        pphi.^2.*(r.^2+a.^2.*cos(th).^2).*(R+a.^2.*Df.*cos(th).^2).^(-1).* ...
        csc(th).^2)).^(-1/2);
      

    dH.dr = dHorbdr + dHsodr;
    dH.dth = dHorbdth + dHsodth;
    dH.dpth = dHorbdpth + dHsodpth;
    dH.dpphi = dHorbdpphi + dHsodpphi;
    dH.dpr = dHdpr_over_pr;

    d2H.d2r = d2Horbd2r + d2Hsod2r;
    d2H.drdpphi = d2Horbdrdpphi + d2Hsodrdpphi;
    d2H.drdpth = d2Horbdrdpth + d2Hsodrdpth;
    d2H.drdth = d2Horbdrdth + d2Hsodrdth;

return

function [A,dA,Gs,dGs,R,dR,Df,dDf] = metric_coeff(r,phi,th,pr,pphi,pth,a)
    A = (a.^2+(-2).*r+r.^2).*(r.^2+a.^2.*cos(th).^2).*(2.*a.^2.*r+a.^2.* ...
        r.^2+r.^4+a.^2.*(a.^2+(-2).*r+r.^2).*cos(th).^2).^(-1);
    Gs = 2.*r.*(2.*a.^2.*r+a.^2.*r.^2+r.^4+a.^2.*(a.^2+(-2).*r+r.^2).*cos( ...
        th).^2).^(-1);
    Df = a.^2+(-2).*r+r.^2;
    R = 2.*a.^2.*r+a.^2.*r.^2+r.^4;

    dA.dr = (r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th).^2).^(-2).* ...
        ((-1).*a.^6+2.*r.^6+a.^2.*r.^3.*((-4)+3.*r)+(-1).*a.^2.*(a.^4+2.* ...
        a.^2.*r.^2+((-4)+r).*r.^3).*cos(2.*th));
    dA.dth = (r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th).^2).^(-2).* ...
        ((-1).*a.^6+2.*r.^6+a.^2.*r.^3.*((-4)+3.*r)+(-1).*a.^2.*(a.^4+2.* ...
        a.^2.*r.^2+((-4)+r).*r.^3).*cos(2.*th));
    dA.d2r = (r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th).^2).^(-3).* ...
        (a.^8+6.*a.^8.*r+(-3).*a.^6.*r.^2+(-6).*a.^4.*r.^3+14.*a.^6.*r.^3+ ...
        12.*a.^4.*r.^4+6.*a.^4.*r.^5+28.*a.^2.*r.^6+(-6).*a.^2.*r.^7+(-4) ...
        .*r.^9+2.*a.^2.*r.*(3.*a.^6+9.*a.^4.*r.^2+r.^5.*((-14)+3.*r)+ ...
        a.^2.*r.^2.*(4+(-6).*r+9.*r.^2)).*cos(2.*th)+(-1).*a.^4.*(a.^4+( ...
        -3).*a.^2.*r.^2+2.*r.^3).*cos(4.*th));
    dA.drdth = (-1).*a.^2.*(r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th) ...
        .^2).^(-3).*(a.^8+a.^4.*(8+(-15).*r).*r.^3+2.*(8+(-3).*r).*r.^7+( ...
        -3).*a.^6.*r.*(2+r)+a.^2.*r.^4.*((-8)+30.*r+(-17).*r.^2)+a.^2.*( ...
        a.^6+a.^2.*r.^3.*((-8)+3.*r)+a.^4.*r.*((-2)+3.*r)+r.^4.*(8+(-6).* ...
        r+r.^2)).*cos(2.*th)).*sin(2.*th);
    dGs.dr = (r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th).^2).^(-2).* ...
        ((-2).*r.^2.*(a.^2+3.*r.^2)+2.*a.^2.*(a.^2+(-1).*r.^2).*cos(th) ...
        .^2);
    dGs.dth = (r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th).^2).^(-2).* ...
        ((-2).*r.^2.*(a.^2+3.*r.^2)+2.*a.^2.*(a.^2+(-1).*r.^2).*cos(th) ...
        .^2);
    dGs.d2r = 4.*(r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th).^2).^( ...
        -3).*(r.^3.*(a.^4+3.*a.^2.*((-2)+r).*r+6.*r.^4)+(-1).*a.^2.*(8.* ...
        a.^2.*r.^3+(-3).*r.^4.*(2+r)+a.^4.*(2+3.*r)).*cos(th).^2+(a.^6.*( ...
        2+(-3).*r)+a.^4.*r.^3).*cos(th).^4);
    dGs.drdth = a.^2.*(r.^4+a.^2.*r.*(2+r)+a.^2.*(a.^2+((-2)+r).*r).*cos(th).^2) ...
        .^(-3).*(a.^6+a.^2.*(14+(-17).*r).*r.^3+2.*(12+(-5).*r).*r.^5+(-6) ...
        .*a.^4.*r.*(1+r)+a.^2.*(a.^4+(-2).*a.^2.*r+(-1).*((-2)+r).*r.^3).* ...
        cos(2.*th)).*sin(2.*th);
    dR.dr = 4.*r.^3+2.*a.^2.*(1+r);
    dR.d2r = 2.*(a.^2+6.*r.^2);
    dDf.dr = 2.*((-1)+r);
    dDf.d2r = 2;
    
    
    
    

return
