function delta = DB_deltalm_fulliota(dyn,flags)

Omega = dyn.Omg;
r = dyn.r;
phi = dyn.phi;
iota = (pi/2-min(dyn.th));
a = dyn.chi1(3);

if flags.r
    rOmg = r;
    v_phi = r.*Omega;
else
    rOmg = r.*(1+a.*r.^(-3/2)).^(2/3);
    v_phi = rOmg.*Omega;
end

x = v_phi.^2;
EulerGamma = 0.57721566490153286060;

%=================================================
% (2,2) mode
%=================================================

delta.l2m2e = x.^3.*((-1/36).*(7.*cos(iota)+cos(3.*iota)).*cot((1/2).*iota).^4.* ...
  csc((1/2).*iota).^8.*csc(4.*phi).^3.*(1+cot(4.*phi).^2+2.*cot(( ...
  1/2).*iota).^4.*cot(4.*phi).*csc(4.*phi)+cot((1/2).*iota).^8.*csc( ...
  4.*phi).^2).^(-2).*((-17)+12.*EulerGamma+36.*log(2)+18.*log(x)) ...
  .^2+(3424/105).*pi.*(7.*cos(iota)+cos(3.*iota)).*(35+28.*cos(2.* ...
  iota)+cos(4.*iota)+8.*cos(4.*phi).*sin(iota).^4).^(-1))+(-8/3).* ...
  x.^(3/2).*(35+28.*cos(2.*iota)+cos(4.*iota)+8.*cos(4.*phi).*sin( ...
  iota).^4).^(-1).*((-105)+119.*cos(iota)+(-84).*cos(2.*iota)+17.* ...
  cos(3.*iota)+(-3).*cos(4.*iota)+192.*EulerGamma.*cos(4.*phi).^2.* ...
  sin((1/2).*iota).^8+576.*log(2).*sin((1/2).*iota).^8+288.*cos(4.* ...
  phi).^2.*log(x).*sin((1/2).*iota).^8+(-24).*cos(4.*phi).*sin(iota) ...
  .^4+12.*EulerGamma.*cos(4.*phi).*sin(iota).^4+6.*cos(4.*phi).*log( ...
  64).*sin(iota).^4+18.*cos(4.*phi).*log(x).*sin(iota).^4+192.* ...
  EulerGamma.*sin((1/2).*iota).^8.*sin(4.*phi).^2+288.*log(x).*sin(( ...
  1/2).*iota).^8.*sin(4.*phi).^2);


delta.l2m2o = (1/3).*x.^(3/2).*((-3).*(6+2.*cos(2.*iota)+cos(2.*(iota+(-1).*phi) ...
  )+(-2).*cos(2.*phi)+cos(2.*(iota+phi))).*((-4)+2.*EulerGamma+log( ...
  64)+3.*log(x))+4.*cos(iota).*(2.*((-5)+3.*EulerGamma+log(64))+9.* ...
  log(x))).*(3+cos(2.*iota)+(-2).*cos(2.*phi).*sin(iota).^2).^(-1)+ ...
  x.^3.*((428/105).*pi.*cos(iota).*(3+cos(2.*iota)+(-2).*cos(2.*phi) ...
  .*sin(iota).^2).^(-1)+(8/9).*cos(iota).*(2.*((-5)+3.*EulerGamma+ ...
  log(64))+9.*log(x)).^2.*sin(iota).^2.*(3+cos(2.*iota)+(-2).*cos( ...
  2.*phi).*sin(iota).^2).^(-2).*sin(2.*phi));

%=================================================
% (2,1) mode
%=================================================

delta.l2m1e = (-1/12).*x.^(3/2).*(6+2.*cos(2.*iota)+cos(2.*(iota+(-2).*phi))+( ...
  -2).*cos(4.*phi)+cos(2.*(iota+2.*phi))).*(3.*(6+2.*cos(2.*iota)+ ...
  cos(2.*(iota+(-2).*phi))+(-2).*cos(4.*phi)+cos(2.*(iota+2.*phi))) ...
  .*((-4)+2.*EulerGamma+log(16)+3.*log(x))+(-8).*cos(iota).*((-17)+ ...
  12.*EulerGamma+36.*log(2)+18.*log(x))).*(3+cos(2.*iota)+(-2).*cos( ...
  4.*phi).*sin(iota).^2).^(-2)+x.^3.*((1712/105).*pi.*cos(iota).*(3+ ...
  cos(2.*iota)+(-2).*cos(4.*phi).*sin(iota).^2).^(-1)+(8/9).*cos( ...
  iota).*((-17)+12.*EulerGamma+36.*log(2)+18.*log(x)).^2.*sin(iota) ...
  .^2.*(3+cos(2.*iota)+(-2).*cos(4.*phi).*sin(iota).^2).^(-2).*sin( ...
  4.*phi));

delta.l2m1o = (-2/3).*x.^(3/2).*(2+cos(4.*iota)+(-2).*cos(2.*phi).*sin(iota).^2+ ...
  cos(2.*iota).*(1+(-4).*cos(2.*phi).*sin(iota).^2)).^(-1).*((-12)+ ...
  10.*cos(3.*iota)+(-6).*cos(4.*iota)+(-12).*cos(3.*iota).*log(2)+ ...
  6.*cos(4.*iota).*log(2)+log(4096)+24.*EulerGamma.*sin((1/2).*iota) ...
  .^4+36.*log(x).*sin((1/2).*iota).^4+48.*cos(iota).^2.*(2.* ...
  EulerGamma+3.*log(x)).*sin((1/2).*iota).^4+2.*cos(iota).*(5+(-6).* ...
  log(2)+24.*(2.*EulerGamma+3.*log(x)).*sin((1/2).*iota).^4)+12.* ...
  cos(2.*phi).*sin(iota).^2+(-6).*EulerGamma.*cos(2.*phi).*sin(iota) ...
  .^2+(-12).*cos(2.*phi).*log(2).*sin(iota).^2+(-9).*cos(2.*phi).* ...
  log(x).*sin(iota).^2+2.*cos(2.*iota).*((-3)+log(8)+(-3).*cos(2.* ...
  phi).*((-4)+2.*EulerGamma+log(16)+3.*log(x)).*sin(iota).^2))+ ...
  x.^3.*((214/105).*pi.*(cos(iota)+cos(3.*iota)).*(2+cos(2.*iota)+ ...
  cos(4.*iota)+(-2).*(1+2.*cos(2.*iota)).*cos(2.*phi).*sin(iota).^2) ...
  .^(-1)+(8/9).*(1+cos(2.*iota)+cos(4.*iota)).*(36.*log(2).^2+(-1).* ...
  log(64).^2+cos(iota).*(2.*((-5)+3.*EulerGamma+log(64))+9.*log(x)) ...
  .^2).*sin(iota).^2.*(2+cos(4.*iota)+(-2).*cos(2.*phi).*sin(iota) ...
  .^2+cos(2.*iota).*(1+(-4).*cos(2.*phi).*sin(iota).^2)).^(-2).*sin( ...
  2.*phi));

%=================================================
% (3,3) mode
%=================================================



%=================================================
% (3,2) mode
%=================================================


%=================================================
% (3,1) mode
%=================================================



%=================================================
% (4,4) mode
%=================================================


%=================================================
% (4,3) mode
%=================================================



%=================================================
% (4,2) mode
%=================================================



%=================================================
% (4,1) mode
%=================================================




return

function p = PolyGamma(a,b)
  p = psi(a,b);
return
