function [Heff,Horb,dHeff,dHorb,dHso] = DB_Hamiltonian_Kerr(obj,X,p,chi1)

%==========================================================================
% Kerr Cartesian Hamiltonian
%==========================================================================

%error('DB_Hamiltonian_Kerr not implemented')

[A,Bp,Bnp,Benp,Gs,dA,dBp,dBnp,dBenp,dGs] = DB_metric_Kerr(X,chi1);

r = norm(X);
L = cross(X,p);
n = X./r;

Horb = sqrt(A.*(1+Bp.*dot(p,p)+Bnp.*dot(n,p).^2+Benp.*(dot(cross(n,p),chi1).^2)));
my_zeros = Horb.*0;

if obj.so_coupling
    Hspin = Gs.*dot(L,chi1);
else
    Hspin = my_zeros;
end

Heff = Horb + Hspin;

x  = X(1);
y  = X(2);
z = X(3);
px = p(1);
py = p(2);
pz = p(3);
dAdx = dA.dx(1);
dAdy = dA.dx(2);
dAdz = dA.dx(3);
dBpdx = dBp.dx(1);
dBpdy = dBp.dx(2);
dBpdz = dBp.dx(3);
dBnpdx = dBnp.dx(1);
dBnpdy = dBnp.dx(2);
dBnpdz = dBnp.dx(3);
dBenpdx = dBenp.dx(1);
dBenpdy = dBenp.dx(2);
dBenpdz = dBenp.dx(3);
dGsdx = dGs.dx(1);
dGsdy = dGs.dx(2);
dGsdz = dGs.dx(3);

dHorbdx = (1/2).*r.^(-3).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2).*(dAdx.*r.^2.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))+A.* ...
        ((-2).*Bnp.*(px.*x+py.*y+pz.*z).*((-1).*px.*r.^2+px.*x.^2+py.*x.* ...
        y+pz.*x.*z)+r.^2.*(dBpdx.*px.^2.*r.^2+dBpdx.*py.^2.*r.^2+dBpdx.* ...
        pz.^2.*r.^2+dBnpdx.*px.^2.*x.^2+2.*dBnpdx.*px.*py.*x.*y+dBnpdx.* ...
        py.^2.*y.^2+2.*dBnpdx.*px.*pz.*x.*z+2.*dBnpdx.*py.*pz.*y.*z+ ...
        dBnpdx.*pz.^2.*z.^2+dBenpdx.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.* ...
        z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1).^2+2.*Benp.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).*dot( ...
        [r.^(-3).*((-1).*pz.*x.*y+py.*x.*z),(-1).*r.^(-3).*(pz.*r.^2+(-1) ...
        .*pz.*x.^2+px.*x.*z),r.^(-3).*(py.*r.^2+(-1).*py.*x.^2+px.*x.*y)], ...
        chi1))));

dHorbdy = (1/2).*r.^(-3).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2).*(dAdy.*r.^2.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))+A.* ...
        ((-2).*Bnp.*(px.*x+py.*y+pz.*z).*((-1).*py.*r.^2+px.*x.*y+py.* ...
        y.^2+pz.*y.*z)+r.^2.*(dBpdy.*px.^2.*r.^2+dBpdy.*py.^2.*r.^2+ ...
        dBpdy.*pz.^2.*r.^2+dBnpdy.*px.^2.*x.^2+2.*dBnpdy.*px.*py.*x.*y+ ...
        dBnpdy.*py.^2.*y.^2+2.*dBnpdy.*px.*pz.*x.*z+2.*dBnpdy.*py.*pz.*y.* ...
        z+dBnpdy.*pz.^2.*z.^2+dBenpdy.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).* ...
        py.*z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1).^2+2.*Benp.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).*dot( ...
        [r.^(-3).*(pz.*r.^2+(-1).*pz.*y.^2+py.*y.*z),r.^(-3).*y.*(pz.*x+( ...
        -1).*px.*z),(-1).*r.^(-3).*(px.*r.^2+py.*x.*y+(-1).*px.*y.^2)], ...
        chi1))));

dHorbdz = (1/2).*r.^(-3).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2).*(dAdz.*r.^2.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))+A.* ...
        ((-2).*Bnp.*(px.*x+py.*y+pz.*z).*((-1).*pz.*r.^2+px.*x.*z+py.*y.* ...
        z+pz.*z.^2)+r.^2.*(dBpdz.*px.^2.*r.^2+dBpdz.*py.^2.*r.^2+dBpdz.* ...
        pz.^2.*r.^2+dBnpdz.*px.^2.*x.^2+2.*dBnpdz.*px.*py.*x.*y+dBnpdz.* ...
        py.^2.*y.^2+2.*dBnpdz.*px.*pz.*x.*z+2.*dBnpdz.*py.*pz.*y.*z+ ...
        dBnpdz.*pz.^2.*z.^2+dBenpdz.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.* ...
        z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1).^2+2.*Benp.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).*dot([( ...
        -1).*r.^(-3).*(py.*r.^2+pz.*y.*z+(-1).*py.*z.^2),r.^(-3).*(px.* ...
        r.^2+pz.*x.*z+(-1).*px.*z.^2),r.^(-3).*((-1).*py.*x.*z+px.*y.*z)], ...
        chi1))));

dHorbdpx = A.*r.^(-1).*(Bnp.*x.*(px.*x+py.*y+pz.*z)+r.^2.*(Bp.*px+Benp.*dot( ...
        [0,r.^(-1).*z,(-1).*r.^(-1).*y],chi1).*dot([r.^(-1).*(pz.*y+(-1).* ...
        py.*z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1))).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*(px.^2+ ...
        py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1).*(( ...
        -1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2);

dHorbdpy = A.*r.^(-1).*(Bnp.*y.*(px.*x+py.*y+pz.*z)+r.^2.*(Bp.*py+Benp.*dot( ...
        [(-1).*r.^(-1).*z,0,r.^(-1).*x],chi1).*dot([r.^(-1).*(pz.*y+(-1).* ...
        py.*z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1))).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*(px.^2+ ...
        py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1).*(( ...
        -1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2);

dHorbdpz = A.*r.^(-1).*(Bnp.*z.*(px.*x+py.*y+pz.*z)+r.^2.*(Bp.*pz+Benp.*dot( ...
        [r.^(-1).*y,(-1).*r.^(-1).*x,0],chi1).*dot([r.^(-1).*(pz.*y+(-1).* ...
        py.*z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1))).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*(px.^2+ ...
        py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1).*(( ...
        -1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2);

%chi1 = chi1./cos(pi/6); %DEBUG
dHsodx = Gs.*dot([0,(-1).*pz,py],chi1)+dGsdx.*dot([pz.*y+(-1).*py.*z,(-1).* ...
        pz.*x+px.*z,py.*x+(-1).*px.*y],chi1);

dHsody = Gs.*dot([pz,0,(-1).*px],chi1)+dGsdy.*dot([pz.*y+(-1).*py.*z,(-1).* ...
        pz.*x+px.*z,py.*x+(-1).*px.*y],chi1);

dHsodz = Gs.*dot([(-1).*py,px,0],chi1)+dGsdz.*dot([pz.*y+(-1).*py.*z,(-1).* ...
        pz.*x+px.*z,py.*x+(-1).*px.*y],chi1);

dHsodpx = Gs.*r.*dot([0,r.^(-1).*z,(-1).*r.^(-1).*y],chi1);
dHsodpy = Gs.*r.*dot([(-1).*r.^(-1).*z,0,r.^(-1).*x],chi1);
dHsodpz = Gs.*r.*dot([r.^(-1).*y,(-1).*r.^(-1).*x,0],chi1);
%chi1 = a; %DEBUG

dHorb.dx = [dHorbdx;  dHorbdy;  dHorbdz];
dHorb.dp = [dHorbdpx; dHorbdpy; dHorbdpz];
dHso.dx = [dHsodx;  dHsody;  dHsodz];
dHso.dp = [dHsodpx; dHsodpy; dHsodpz];

if obj.so_coupling
    dHeff.dx = dHorb.dx + dHso.dx;
    dHeff.dp = dHorb.dp + dHso.dp;
else
    dHeff.dx = dHorb.dx;
    dHeff.dp = dHorb.dp;
end

%{
dH.H    = H;
dH.Heff = Heff;
dH.Horb = Horb;
dH.Gs   = Gs;
dH.A    = A;
dH.Bp   = Bp;
dH.Bnp  = Bnp;
dH.dp = dHeff.dp;
%}

end
