function [Heff,Horb,dHeff,dHorb] = DB_Hamiltonian_Kerr_star(X,ps,chi1)

%==========================================================================
% FIXME
% Kerr Cartesian Hamiltonian with tortoise momentum
% Not implemented correctly (compare with 'kerr')
% Derivatives of H wrt x,y,z are identical to the ones used in 'kerr'
% Derivatives wrt to momenta are calculated and implemented by hand, not using the mathematica notebook (maybe that's the problem)
%==========================================================================

[A,Bp,Bnp,Benp,Gs,dA,dBp,dBnp,dBenp,dGs] = DB_metric_Kerr(X,chi1);
[T,Tinv,dT,dTinv,xi,dxi] = DB_Tmatrix(X,chi1);

pxs = ps(1);
pys = ps(2);
pzs = ps(3);

r = norm(X);
L = cross(X,Tinv*ps);
n = X./r;

Horb = sqrt(A.*(1+Bp.*dot(Tinv*ps,Tinv*ps)+Bnp.*dot(n,Tinv*ps).^2+Benp.*(dot(cross(n,Tinv*ps),chi1).^2)));
Hspin = Gs.*dot(L,chi1);

Heff = Horb + Hspin;

x  = X(1);
y  = X(2);
z = X(3);
dAdx = dA.dx(1);
dAdy = dA.dx(2);
dAdz = dA.dx(3);
dBpdx = dBp.dx(1);
dBpdy = dBp.dx(2);
dBpdz = dBp.dx(3);
dBnpdx = dBnp.dx(1);
dBnpdy = dBnp.dx(2);
dBnpdz = dBnp.dx(3);
dBenpdx = dBenp.dx(1);
dBenpdy = dBenp.dx(2);
dBenpdz = dBenp.dx(3);
dGsdx = dGs.dx(1);
dGsdy = dGs.dx(2);
dGsdz = dGs.dx(3);

pvec = Tinv*ps;
px = pvec(1);
py = pvec(2);
pz = pvec(3);     


dHorbdx = (1/2).*r.^(-3).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2).*(dAdx.*r.^2.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))+A.* ...
        ((-2).*Bnp.*(px.*x+py.*y+pz.*z).*((-1).*px.*r.^2+px.*x.^2+py.*x.* ...
        y+pz.*x.*z)+r.^2.*(dBpdx.*px.^2.*r.^2+dBpdx.*py.^2.*r.^2+dBpdx.* ...
        pz.^2.*r.^2+dBnpdx.*px.^2.*x.^2+2.*dBnpdx.*px.*py.*x.*y+dBnpdx.* ...
        py.^2.*y.^2+2.*dBnpdx.*px.*pz.*x.*z+2.*dBnpdx.*py.*pz.*y.*z+ ...
        dBnpdx.*pz.^2.*z.^2+dBenpdx.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.* ...
        z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1).^2+2.*Benp.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).*dot( ...
        [r.^(-3).*((-1).*pz.*x.*y+py.*x.*z),(-1).*r.^(-3).*(pz.*r.^2+(-1) ...
        .*pz.*x.^2+px.*x.*z),r.^(-3).*(py.*r.^2+(-1).*py.*x.^2+px.*x.*y)], ...
        chi1))));

dHorbdy = (1/2).*r.^(-3).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2).*(dAdy.*r.^2.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))+A.* ...
        ((-2).*Bnp.*(px.*x+py.*y+pz.*z).*((-1).*py.*r.^2+px.*x.*y+py.* ...
        y.^2+pz.*y.*z)+r.^2.*(dBpdy.*px.^2.*r.^2+dBpdy.*py.^2.*r.^2+ ...
        dBpdy.*pz.^2.*r.^2+dBnpdy.*px.^2.*x.^2+2.*dBnpdy.*px.*py.*x.*y+ ...
        dBnpdy.*py.^2.*y.^2+2.*dBnpdy.*px.*pz.*x.*z+2.*dBnpdy.*py.*pz.*y.* ...
        z+dBnpdy.*pz.^2.*z.^2+dBenpdy.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).* ...
        py.*z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1).^2+2.*Benp.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).*dot( ...
        [r.^(-3).*(pz.*r.^2+(-1).*pz.*y.^2+py.*y.*z),r.^(-3).*y.*(pz.*x+( ...
        -1).*px.*z),(-1).*r.^(-3).*(px.*r.^2+py.*x.*y+(-1).*px.*y.^2)], ...
        chi1))));

dHorbdz = (1/2).*r.^(-3).*(A.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))).^( ...
        -1/2).*(dAdz.*r.^2.*(Bnp.*(px.*x+py.*y+pz.*z).^2+r.^2.*(1+Bp.*( ...
        px.^2+py.^2+pz.^2)+Benp.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).^2))+A.* ...
        ((-2).*Bnp.*(px.*x+py.*y+pz.*z).*((-1).*pz.*r.^2+px.*x.*z+py.*y.* ...
        z+pz.*z.^2)+r.^2.*(dBpdz.*px.^2.*r.^2+dBpdz.*py.^2.*r.^2+dBpdz.* ...
        pz.^2.*r.^2+dBnpdz.*px.^2.*x.^2+2.*dBnpdz.*px.*py.*x.*y+dBnpdz.* ...
        py.^2.*y.^2+2.*dBnpdz.*px.*pz.*x.*z+2.*dBnpdz.*py.*pz.*y.*z+ ...
        dBnpdz.*pz.^2.*z.^2+dBenpdz.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.* ...
        z),r.^(-1).*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)], ...
        chi1).^2+2.*Benp.*r.^2.*dot([r.^(-1).*(pz.*y+(-1).*py.*z),r.^(-1) ...
        .*((-1).*pz.*x+px.*z),r.^(-1).*(py.*x+(-1).*px.*y)],chi1).*dot([( ...
        -1).*r.^(-3).*(py.*r.^2+pz.*y.*z+(-1).*py.*z.^2),r.^(-3).*(px.* ...
        r.^2+pz.*x.*z+(-1).*px.*z.^2),r.^(-3).*((-1).*py.*x.*z+px.*y.*z)], ...
        chi1))));

dHsodx = Gs.*dot([0,(-1).*pz,py],chi1)+dGsdx.*dot([pz.*y+(-1).*py.*z,(-1).* ...
        pz.*x+px.*z,py.*x+(-1).*px.*y],chi1);

dHsody = Gs.*dot([pz,0,(-1).*px],chi1)+dGsdy.*dot([pz.*y+(-1).*py.*z,(-1).* ...
        pz.*x+px.*z,py.*x+(-1).*px.*y],chi1);

dHsodz = Gs.*dot([(-1).*py,px,0],chi1)+dGsdz.*dot([pz.*y+(-1).*py.*z,(-1).* ...
        pz.*x+px.*z,py.*x+(-1).*px.*y],chi1);

xvers = [1;0;0];
yvers = [0;1;0];
zvers = [0;0;1];

dHorbdpxs = A./Horb.*(Bp.*dot((Tinv*ps),Tinv*xvers)+Bnp.*dot(n,Tinv*ps).* ...
        dot(n,Tinv*xvers) + Benp.*dot(cross(n,Tinv*ps),cross(n,Tinv*xvers)));

dHorbdpys = A./Horb.*(Bp.*dot((Tinv*ps),Tinv*yvers)+Bnp.*dot(n,Tinv*ps).* ...
        dot(n,Tinv*yvers) + Benp.*dot(cross(n,Tinv*ps),cross(n,Tinv*yvers)));

dHorbdpzs = A./Horb.*(Bp.*dot((Tinv*ps),Tinv*zvers)+Bnp.*dot(n,Tinv*ps).* ...
        dot(n,Tinv*zvers) + Benp.*dot(cross(n,Tinv*ps),cross(n,Tinv*zvers)));

dHsodpxs = Gs.*r.*(dot(cross(n,Tinv*xvers),chi1));
dHsodpys = Gs.*r.*(dot(cross(n,Tinv*yvers),chi1));
dHsodpzs = Gs.*r.*(dot(cross(n,Tinv*zvers),chi1));

dHorb.dx   = [dHorbdx;   dHorbdy;   dHorbdz];
dHorb.dps  = [dHorbdpxs; dHorbdpys; dHorbdpzs];
dHso.dx    = [dHsodx;    dHsody;    dHsodz];
dHso.dps   = [dHsodpxs;  dHsodpys;  dHsodpzs];
dHorb.dp = dHorb.dps'*T;
dHso.dp = dHso.dps'*T;

dHeff.dx = dHorb.dx + dHso.dx;
dHeff.dps = dHorb.dps + dHso.dps;
dHeff.dp = dHeff.dps'*T;

% do not evolve spin
dHeff.dchi1 = 0*dHeff.dx;
dHeff.dchi2 = dHeff.dchi1; 

my_zeros = Heff*0;
%{
H = my_zeros+1;

dH.dx    = my_zeros;
%dH.dp    = my_zeros;
dH.dchi1 = my_zeros;
dH.dchi2 = my_zeros;

dH.H    = H;
dH.Heff = Heff;
dH.Horb = Horb;
dH.Gs   = Gs;
dH.Bp   = Bp;
dH.Bnp  = Bnp;
dH.A = A;
dH.dp = dHeff.dps'*T; %needed to compute angular frequency

%}
end