% GENERATE_GOLDEN_MASTER  Snapshot reference trajectories for regression testing.
%
%   Run this ONCE, on code whose output you currently trust, to create
%   golden_master.mat. testGoldenMaster.m then reruns these same inputs
%   and checks the output hasn't changed.
%
%   This test does NOT tell you the physics is correct -- testKnownLimits
%   and testGeodesicConservation are for that. It only tells you whether
%   a change (e.g. the CSE rewrite of DB_metric_Kerr) altered the output.
%   If a change is EXPECTED to alter the output (a real physics fix),
%   regenerate this file deliberately, and look at what changed and by how
%   much before committing the new golden file -- never regenerate it just
%   to make a red test go green without understanding why it went red.
%
%   Add more cases below as you exercise more of the parameter space:
%   different spins, inclinations, plunges vs. spherical orbits, and (once
%   you've decided how DB_postspherical_ICs should handle it) both the
%   old th0-based and new iota-based input styles for the same physical
%   orbit.

cases = {};

cases{end+1} = struct(...
    'chi1',[0 0 0.5], ...
    'iota',deg2rad(30), ...
    'r0',12, ...
    'ICs','spherical', ...
    'geodesics',1, ...
    'Tmax',1500, ...
    'dt',0.25, ...
    'reltol',1e-12, ...
    'abstol',1e-12, ...
    'verbose',0 ...
);

cases{end+1} = struct(...
    'chi1',[0 0 0.9], ...
    'iota',deg2rad(150), ...
    'r0',10, ...
    'ICs','spherical', ...
    'geodesics',1, ...
    'Tmax',1500, ...
    'dt',0.25, ...
    'reltol',1e-12, ...
    'abstol',1e-12, ...
    'verbose',0 ...
);

cases{end+1} = struct(...
    'chi1',[0 0 0.7], ...
    'iota',deg2rad(20), ...
    'r0',5, ...
    'ICs','post-spherical', ...
    'geodesics',0, ...
    'dt',0.25, ...
    'reltol',1e-12, ...
    'abstol',1e-12, ...
    'verbose',0 ...
);


cases{end+1} = struct(...
    'chi1',[0 0 0.2], ...
    'iota',deg2rad(145), ...
    'r0',5, ...
    'ICs','post-spherical', ...
    'geodesics',0, ...
    'dt',0.25, ...
    'reltol',1e-12, ...
    'abstol',1e-12, ...
    'verbose',0 ...
);

golden = struct();
for i = 1:numel(cases)
    fprintf('case %d...\n',i)
    dyn = DB_class(cases{i});
    key = sprintf('case%d', i);

    golden.(key).input = cases{i};
    golden.(key).t     = dyn.t;
    golden.(key).r     = dyn.r;
    golden.(key).th    = dyn.th;
    golden.(key).phi   = dyn.phi;
    golden.(key).Heff  = dyn.Heff;
    golden.(key).C     = dyn.C;
    golden.(key).pphi  = dyn.pphi;
end

outfile = fullfile(fileparts(mfilename('fullpath')), 'golden_master.mat');
save(outfile, 'golden');
fprintf('Golden master saved to %s (%d cases).\n', outfile, numel(cases));
